### ISSUE TITLE
** Failed to parse provided arguments

### ISSUE THREAD

**Issue by BRANOPODCAST** [0xnobody/vmpdump#15]
![photo_2021-03-21_06-39-38](https://user-images.githubusercontent.com/15612504/111895078-58de3700-8a10-11eb-8187-f1163507dc85.jpg)

**Comment by heinrich5991** [comment]
You need to specify the module name, try passing the empty string.
`VMPDump.exe 9464 ""`

**Comment by 0xnobody** [comment]
@heinrich5991 is correct. You must provide a module name. You may provide an empty string if you want to use the executable module.
