### ISSUE TITLE
Dumped File Doesn't Run

### ISSUE THREAD

**Issue by ghost** [0xnobody/vmpdump#22]
After running vmpdump on a vmprotect packed file the file doesn't run. I have tried compilng VMPDUMP from source and use older version. I also tried changing the code of the packed file. It won't work. No one has made a issue on this so I don't know if it is just me.
The file is written in C++. When I run the file in CMD it doesn't show anything. However when I run the vmp packed file before running VMPDUMP it works fine. Please Help Me if I'm doing something wrong.

Commands used:

VMPDump.exe 4126 "" -disable-reloc

The command works successfully but clicking on the file it doesn't run.
This is the output
![image](https://user-images.githubusercontent.com/100746282/189470496-d213302f-e0ee-4eb0-bb7a-bb654d8886f3.png)

**Comment by hotline1337** [comment]
fix the start address to initialize the security cookie and jump to seh main

**Comment by ghost** [comment]
How would I  do that I am new to doing all of this.

> fix the start address to initialize the security cookie and jump to seh main

**Comment by ghost** [comment]
Nevermind I have fixed the issue by watching a video thanks.

**Comment by realmCode** [comment]
> Nevermind I have fixed the issue by watching a video thanks.

could you please send video, I am getting same trouble, someexe.VMPDUMP.exe doesnt open.
