### ISSUE TITLE
Compile assist

### ISSUE THREAD

**Issue by DigiAngel** [0xnobody/vmpdump#4]
Would love to compile this, but I don't have any experience with VTIL or capstone/keystone on windows.  Any pointers on how to get this setup?  Thank you!

**Comment by 0xnobody** [comment]
Hey,
Compiling VTIL-Core on windows is as easy as cloning the project, and building in VS via CMake. All deps are fetched and built automatically. Then you must just redirect the include/library directories of VMPDump to the correct paths.

**Comment by DigiAngel** [comment]
Thank you!
