### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by paindustry** [0xnobody/vmpdump#7]
[*] Error: Assertion failure, mem_base.is_register() && mem_base.bit_count() ==
64 at ..\..\..\Dependencies\VTIL-Core\VTIL-Architecture\routine\instruction.cpp:
61

**Comment by 0xnobody** [comment]
Please send the file.

**Comment by 0xnobody** [comment]
Didn't receive the file in over a month, so assume that the issue has been resolved.
